#Makefile
#target all: compiles all of the assignments
all: list.hpp  list.cpp items.hpp items.cpp main.cpp
	g++ -std=c++0x  list.hpp list.cpp items.hpp items.cpp main.cpp  -o groceries

clean:
	rm -rf *o groceries
