#Makefile
#target all: compiles all of the assignments
all: list.hpp list.cpp filo.cpp listTwo.hpp listTwo.cpp fifo.cpp
	g++ -std=c++0x  list.hpp list.cpp filo.cpp  -o filo
	g++ -std=c++0x  listTwo.hpp listTwo.cpp fifo.cpp -o fifo

one:
	g++ -std=c++0x  list.hpp list.cpp filo.cpp  -o filo
two:
	g++ -std=c++0x  listTwo.hpp listTwo.cpp fifo.cpp -o fifo


clean:
	rm -rf *o filo
