#Makefile
#target all: compiles all of the assignments
all: dice.hpp dice.cpp characters.hpp characters.cpp main.cpp
	g++ -std=c++0x  dice.hpp dice.cpp characters.hpp characters.cpp main.cpp  -o TestFile

clean:
	rm -rf *o TestFile
