#Makefile
#target all: compiles all of the assignments
all: functions.hpp stack.cpp queue.hpp queue.cpp
	g++ -std=c++0x  functions.hpp stack.cpp  -o stacklike
	g++ -std=c++0x  queue.hpp queue.cpp  -o queuelike

clean:
	rm -rf *o stacklike
